name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  testMacOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: ./run_tests_mac.sh

  testIOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: ./run_tests_ios.sh

  buildSwiftPackage:
    needs: [ testMacOS, testIOS ]
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: swift build -v

  buildCarthage:
    needs: [ testMacOS, testIOS ]
    name: Build Carthage
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: carthage build --configuration Release --no-skip-current --use-xcframeworks

  auto-merge:
    needs: [buildSwiftPackage, buildCarthage]
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: auto-merge
        if: |
          github.actor == 'dependabot[bot]' &&
          github.event_name == 'pull_request'
        run: |
          ./merge_dependabot.sh
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          # this secret needs to be in the settings.secrets.dependabot
          GITHUB_TOKEN: ${{secrets.GH_ACTION_TOKEN}}
