name: Test Current Release

on: 
  workflow_dispatch:
  schedule:
    - cron: '45 16 * * 0'  # <https://crontab.guru/#45_16_*_*_0> - "At 16:45 UTC on Sunday"  
    - cron: '30 18 * * 0'
    - cron: '30 19 * * 0'  

jobs:
  buildAndTest:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repository: approvals/ApprovalTests.Swift.StarterProject.MacOS
    - name: Build
      run: ./build.sh
    - name: Run tests
      run: ./run_tests.sh
