name: Test Current Release

on: 
  workflow_dispatch:
  schedule:
    - cron: '00 22 * * 2'  # <https://crontab.guru/#00_22_*_*_2>

jobs:
  buildAndTestMacOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
      with:
        repository: approvals/ApprovalTests.Swift.StarterProject.MacOS
        path: ApprovalTests.Swift.StarterProject.MacOS
    - name: Build
      run: |
        cd ApprovalTests.Swift.StarterProject.MacOS
        ./build.sh
    - name: Run tests
      run: |
        cd ApprovalTests.Swift.StarterProject.MacOS
        ./run_tests.sh
  buildAndTestiOs:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
      with:
        repository: approvals/ApprovalTests.Swift.StarterProject.iOs
        path: ApprovalTests.Swift.StarterProject.iOs
    - name: Build
      run: |
        cd ApprovalTests.Swift.StarterProject.iOs
        ./build.sh
    - name: Run tests
      run: |
        cd ApprovalTests.Swift.StarterProject.iOs
        ./run_tests.sh
