name: Test Current Release

on: 
  workflow_dispatch:
  schedule:
    - cron: '00 23 * * 2'  # <https://crontab.guru/#00_23_*_*_2>

jobs:
  buildAndTest:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repository: approvals/ApprovalTests.Swift.StarterProject.MacOS
        path: ApprovalTests.Swift.StarterProject.MacOS
    - name: Build
      run: |
        cd ApprovalTests.Swift.StarterProject.MacOS
        ./build.sh
    - name: Run tests
      run: |
        cd ApprovalTests.Swift.StarterProject.MacOS
        ./run_tests.sh
